language: node_js
node_js:
  - 4.0.0
  - 4.3.0
  - 6.5.0

os:
  - linux

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

install:
  - npm install
  - npm install -g codecov

script:
  - 'npm test'
  - 'npm run lint'
  - 'npm run cover'
  - 'codecov'